---
- name: tasks for 3-tier apps
  hosts: all
  gather_facts: false
  become: true
  
  tasks:
    - name: check disk usage
      command: /usr/bin/df -h
      register: test_out

    - debug:
        msg: "{{ test_out.stdout_lines }}"
